### ISSUE TITLE
Drupal Views & jquery Update Module

### ISSUE THREAD

**Issue by danielscherber** [code-rider/drupal_threesixty_slider#2]
Is it possible that there are issues?

If I set the jQuery Update module to use Drupal’s default jQuery, the 360° works, if I set it to version 1.10 it breaks. It breaks with versions above 1.7. Possible to fix this?

**Comment by code-rider** [comment]
hi
this issue is fixed at https://www.drupal.org/node/2529830#comment-10123338
thanks
